### ISSUE TITLE
markdown formatting error in vignettes

### ISSUE THREAD

**Issue by richardjtelford** [bmaitner/RBIEN#40]
In the BIEN vignette, there should be

- a space after the ### to get a heading
- a bank line before unordered lists to get the list not text with asterisk

In the BIEN_tutorial vignette

- the yaml is malformed - see other vignette for valid yaml
- line 39 refers to RBIEN

Can send a pull request if you want

**Comment by bmaitner** [comment]
Thanks, Richard.  I'll get this done.

**Comment by bmaitner** [comment]
Pushed the fixes to Github
